### ISSUE TITLE
Pruning on a schedule

### ISSUE THREAD

**Issue by jackcruden** [insenseanalytics/laravel-telescope-pruning#1]
This is excellent! The TELESCOPE_WHITELIST_MONITORED_TAG_PRUNING config option is especially useful. 

Is it pruning Telescope entries with every request? Is there an option to attach a scheduler?

**Comment by paras-malhotra** [comment]
Yes, currently it is pruning entries with every request. However, it does not block the response as the pruning happens after the worker cycle before kernel shutdown.

I think scheduling should definitely be added as a feature in the package. Until we do so, you can probably create a command like so:

```php
public function handle()
{
    (new PruneEntries(app()))->prune();
}
```

If you want to turn off the pruning with every request, you can simply add the `TelescopePruningServiceProvider` to `dont-discover` in your `composer.json` like so:

```json
"extra": {
    "laravel": {
        "dont-discover": [
            "insenseanalytics/laravel-telescope-pruning"
        ]
    }
},
```

**Comment by paras-malhotra** [comment]
In v0.1.2, we have added:
- The ability to turn off telescope pruning on every request
- `TrimCommand` to prune entries. You may schedule this command using Laravel's [task scheduling](https://laravel.com/docs/5.7/scheduling)
